export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const LEADSDATA = "LEADSDATA";
export const DEALSDATA = "DEALSDATA";
export const CONTACTDATA = "CONTACTDATA";
export const CHANGE_PRIMARY_THEME = "CHANGE_PRIMARY_THEME";
export const CHANGE_SECONDARY_THEME = "CHANGE_SECONDARY_THEME";
export const CHANGE_NOTIFICATION_COUNT = "CHANGE_NOTIFICATION_COUNT";