import { StyleSheet } from "react-native";
import { colors } from "../../themes/colors";
export const styles = StyleSheet.create({
    mainView: {
        flex: 1,
        backgroundColor: colors.lightGraay,
    },headerView:{
        marginHorizontal:20,
        borderRadius:5,
        marginBottom:2,
        backgroundColor:colors.whiteColor
    },
    headerText:{
        fontSize:40,
        color:colors.blackTextColor,
        fontWeight:'bold'
    },
    line:{
        height:0.8,
        backgroundColor:colors.greyColor
    },
    line1:{
        height:0.2,
        backgroundColor:colors.greyColor
    },
    line3:{
        height:1.3,
        backgroundColor:colors.greyColor
    },
    QouteText:{
        fontSize:23,
        paddingTop:10,
        paddingLeft:20,
        fontWeight:'600',
    },
    QouteText1:{
        fontSize:16,
        padding:15,
        fontWeight:'500'
    },NewTextView:{
        flexDirection:'row',
        alignItems:'center',
        padding:10,
    },title1:{
        fontSize:17,
        fontWeight:'500',
        color:colors.blackTextColor
    },area:{
        height:50,
        borderBottomColor:colors.greyColor,
        borderBottomWidth:1.2
    },line5:{
        borderBottomColor:colors.greyColor,
        borderBottomWidth:1,
        marginVertical:10
    },
    nameView:{
        backgroundColor:colors.primaryColor,
        width:70,
        height:70,
        borderRadius:35,
        marginTop:40,
        justifyContent:'center',
        alignItems:'center'
    },
    nameText:{
        fontSize:25,
        fontWeight:'700',
        color:colors.whiteColor
    },
    subTitleText:{
        fontSize:16,
        fontWeight:'400',
        color:colors.greyColor,
        marginBottom:8
    },
    titleText:{
        fontSize:17,
        color:colors.greyColor,
        padding:15,
        fontWeight:'500'
    }
})